### ISSUE TITLE
Add data tracking

### ISSUE THREAD

**Issue by leg2015** [leg2015/Aagos#1]
- [x] Decide on overlap metric
     * Overlap histogram
- [x] Finish data collection function 
     * AagosOrg, adding tracking info

- [x] Add all statistics data tracking
    * histogram
    * neighboring genes
    * average gene overlap
- [x] histogram
     * Number of neutral sites
     * Number of single overlap sites
    * num sites with overlap of >1
- [x] Number of neighbor genes
- [x] Average gene overlap
                   * Average number of genes per site 
                   *  `num_genes * gene_length / genome_length`
- [x] Add snapshot of representative organism for statistics update
- [x] Add data tracking for snapshots
- [x] Snapshot org data
                   * Gene start positions
                   * Genome length
                   * Fitness
- [x] Move data calculation to separate function that node pulls from only on snapshot updates
- [x] Hook in data collection to world creation

**Comment by leg2015** [comment]
Data tracking is fully implemented in Aagos. Still needs to be tested but all relevant data files and integration has been added, so going to close this issue for now.
