### ISSUE TITLE
Test data tracking

### ISSUE THREAD

**Issue by leg2015** [leg2015/Aagos#3]
- [x] Test overall data tracking
   * run a test example see if data output makes sense
- [x] Test histogram overlap calculation
- [x] Test avg # genes per site calculation
- [x] Test number of neighbor genes calculation

- [x] Retest overall data tracking
   * run a very small pop and see what output should be, compare to hand-calculated values to confirm all values are as intended

**Comment by leg2015** [comment]
Data not getting added to the representative or statistics file. However, snapshot file is adding in all its data correctly. Need to find out why rep and stats files aren't getting updated. Also, discovered when Aagos hits its max gens, get a malloc error #4

**Comment by leg2015** [comment]
Currently, the histogram of each organism's overlap is not properly being created. The bins in each organism's histogram are not of width 1, which is worrisome. Need to investigate more to see if why the histogram is not being correctly instantiated.

**Comment by leg2015** [comment]
### Finally @emilydolson and I got all the data tracking appropriately tested and confirms it functions as intended!
 ##### Histogram
    * Histogram calculation in `AagosOrg` wasn't exactly correct, had an off-by-one error but that is fixed now. 
    * Also be careful comparing `size_t` and `int`, as that was causing weird errors in the comparisons to calculate the histogram.
   * Histogram bins also weren't being accurately counted. More bins than necessary were being created in the histogram but that was also resolved
   * Magic numbers to calculate number of bins were removed and replaced with member variables in `AagosOrg` and `AagosWorld`.
#### Random Seed
    * The seed to the random stored in the world was updated in the `AagosWorld` class to reflect the value passed in as a parameter.
#### Testing Files
   * Created a separate native cc file `AagosTests` to run some testing for these functions. 
   * Hooked this test file into the `makefile` in order to compile and debug the code appropriately.
  * Also created a small bash script to test the data tracking
### Todo
  * Still need to incorporate formal testing of data tracking, might make a separate issue
